### ISSUE TITLE
Clarification on License

### ISSUE THREAD

**Issue by kiranandcode** [HexHive/BOPC#15]
Hi, Thanks for the great work, and the excellent artefact! It really was very easy to set up and run locally!

I'm interested in building on top of this work --- could you clarify the license under which this has been released?

sorry to be a bother, I realise that this project hasn't been updated in a while.

**Comment by ispoleet** [comment]
Hi, I think project is under Apache License. You are welcome to use it in any way that you like, but please don't forget to cite us :)

**Comment by kiranandcode** [comment]
Alright, perfect, thanks! If you have the chance, it would be good if you could list that explicitly in the repository.

> but please don't forget to cite us :)

Of course :smile:! That's a given!
