### ISSUE TITLE
Would you provide verified entry points for succeeded test cases?

### ISSUE THREAD

**Issue by 1dfuzz-anon** [HexHive/BOPC#4]
I find it very difficult to get any solutions for payload **print.spl** in target evaluating binaries other than your example in README.md.

**Comment by ispoleet** [comment]
Entry points are hard to find and orthogonal to our problem. Finding them is pretty hard as you need to analyze the vulnerability. To alleviate this problem I hided an easter egg in the code: If you set the entry
point to -1, BOPC assumes that the entry point is anywhere (i.e., wildcard entry point). If a solution is 
found, it will have no entry point, However you know where a solution is, so you can set an entry point
close to the solution (usually few basic blocks back) and re-run BOPC with that entry point to get a full
solution.

It's definitely not the best way to do it, but it something that works :)
